all:
  hosts:
    azwu2nhsw001:
      variable: value
  vars:
    global_var: global_value
  children:
    windows:
      hosts:
        azwu2nhsw001:
      vars:
        # ansible_shell_type: powershell
        ansible_user: "{{ lookup('ansible.builtin.env', 'SERVER_ADMIN_USER') }}"
        ansible_password: "{{ lookup('ansible.builtin.env', 'SERVER_ADMIN_PASSWORD') }}"
        ansible_connection: psrp
        ansible_port: 5985